---
# tasks file for instalar-kubeadm
- name: "Instalar kubeadm"
  ansible.builtin.apt:
    name: ["apt-transport-https", "ca-certificates", "curl"]
    state: present
    update_cache: true
- name: "Prepara repositorio"
  ansible.builtin.lineinfile:
    line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    create: true
    path: /etc/apt/sources.list.d/kubernetes.list
- name: "Baixa chave pública"
  ansible.builtin.shell:
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
- name: "Instalar kubectl, kubeadm e kubelet"
  ansible.builtin.apt:
    name: ["kubelet", "kubeadm", "kubectl"]
    state: present
    update_cache: true