- name: Copiar kubeconfig
  hosts:
    - kubenode01
    - kubenode02
  tasks:
    - name: "Criar diretório .kube"
      ansible.builtin.file:
        path: /home/vagrant/.kube
        state: directory
    - name: Copiar kubeconfig
      ansible.builtin.copy:
        src: ../config
        dest: /home/vagrant/.kube/config