---
# tasks file for instalar-containerd
- name: "Preparar instalação containerd"
  become: true
  apt: 
    name: ["ca-certificates", "curl", "gnupg"]
- name: "Instalar keyrings docker"
  become: true
  vars:
      commands:
        - install -m 0755 -d /etc/apt/keyrings
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
        - chmod a+r /etc/apt/keyrings/docker.gpg
  shell:
    cmd: "{{ item }}"
  loop: "{{ commands }}"
- name: "Prepara repositório containerd"
  become: true
  shell: >-
    echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] 
    https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable"
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: "Instalar containerd"    
  become: true
  apt:
    name: containerd.io
    state: present
    update_cache: true
- name: "Instalar docker cli"    
  become: true
  apt:
    name: docker-ce-cli
    state: present
    update_cache: true    
- name: "Instalar docker engine"    
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: true    
- name: "Instalar docker-buildx-plugin"    
  become: true
  apt:
    name: docker-buildx-plugin
    state: present
    update_cache: true        
- name: "Instalar docker-compose-plugin"    
  become: true
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: true