---
# tasks file for cluster-join
- name: "Criar diretório .kube"
  ansible.builtin.file:
    path: /home/vagrant/.kube
    state: directory
- name: Copiar kubeconfig
  ansible.builtin.copy:
    src: config
    dest: /home/vagrant/.kube/config
- name: "Ajustar ip do worker node no kubelet"
  become: true
  lineinfile:
    line: "Environment=\"KUBELET_EXTRA_ARGS=--node-ip={{ ansible_facts['enp0s8']['ipv4']['address'] }}\""
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    state: present
    insertafter: '^\[Service'
- name: "Reiniciar kubelet"
  become: true
  ansible.builtin.systemd_service:
    name: kubelet
    daemon_reload: true
    state: restarted
- name: Copiar comando do kubeadmjoin
  ansible.builtin.copy:
    src: kubeadmjoin
    dest: /home/vagrant/kubeadmjoin
- name: Juntar-se ao cluster
  become: true
  ansible.builtin.shell:
    cmd: chmod +x /home/vagrant/kubeadmjoin && bash /home/vagrant/kubeadmjoin